/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "k8s.io/api/certificates/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	certificatesv1alpha1 "k8s.io/client-go/applyconfigurations/certificates/v1alpha1"
	testing "k8s.io/client-go/testing"
)

// FakeWorkloadCertificates implements WorkloadCertificateInterface
type FakeWorkloadCertificates struct {
	Fake *FakeCertificatesV1alpha1
	ns   string
}

var workloadcertificatesResource = v1alpha1.SchemeGroupVersion.WithResource("workloadcertificates")

var workloadcertificatesKind = v1alpha1.SchemeGroupVersion.WithKind("WorkloadCertificate")

// Get takes name of the workloadCertificate, and returns the corresponding workloadCertificate object, and an error if there is any.
func (c *FakeWorkloadCertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workloadcertificatesResource, c.ns, name), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}

// List takes label and field selectors, and returns the list of WorkloadCertificates that match those selectors.
func (c *FakeWorkloadCertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkloadCertificateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workloadcertificatesResource, workloadcertificatesKind, c.ns, opts), &v1alpha1.WorkloadCertificateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkloadCertificateList{ListMeta: obj.(*v1alpha1.WorkloadCertificateList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkloadCertificateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workloadCertificates.
func (c *FakeWorkloadCertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workloadcertificatesResource, c.ns, opts))

}

// Create takes the representation of a workloadCertificate and creates it.  Returns the server's representation of the workloadCertificate, and an error, if there is any.
func (c *FakeWorkloadCertificates) Create(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.CreateOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workloadcertificatesResource, c.ns, workloadCertificate), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}

// Update takes the representation of a workloadCertificate and updates it. Returns the server's representation of the workloadCertificate, and an error, if there is any.
func (c *FakeWorkloadCertificates) Update(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.UpdateOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workloadcertificatesResource, c.ns, workloadCertificate), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkloadCertificates) UpdateStatus(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.UpdateOptions) (*v1alpha1.WorkloadCertificate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workloadcertificatesResource, "status", c.ns, workloadCertificate), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}

// Delete takes name of the workloadCertificate and deletes it. Returns an error if one occurs.
func (c *FakeWorkloadCertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(workloadcertificatesResource, c.ns, name, opts), &v1alpha1.WorkloadCertificate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkloadCertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workloadcertificatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkloadCertificateList{})
	return err
}

// Patch applies the patch and returns the patched workloadCertificate.
func (c *FakeWorkloadCertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkloadCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workloadcertificatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied workloadCertificate.
func (c *FakeWorkloadCertificates) Apply(ctx context.Context, workloadCertificate *certificatesv1alpha1.WorkloadCertificateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	if workloadCertificate == nil {
		return nil, fmt.Errorf("workloadCertificate provided to Apply must not be nil")
	}
	data, err := json.Marshal(workloadCertificate)
	if err != nil {
		return nil, err
	}
	name := workloadCertificate.Name
	if name == nil {
		return nil, fmt.Errorf("workloadCertificate.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workloadcertificatesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeWorkloadCertificates) ApplyStatus(ctx context.Context, workloadCertificate *certificatesv1alpha1.WorkloadCertificateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	if workloadCertificate == nil {
		return nil, fmt.Errorf("workloadCertificate provided to Apply must not be nil")
	}
	data, err := json.Marshal(workloadCertificate)
	if err != nil {
		return nil, err
	}
	name := workloadCertificate.Name
	if name == nil {
		return nil, fmt.Errorf("workloadCertificate.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workloadcertificatesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.WorkloadCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkloadCertificate), err
}
