/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WorkloadCertificateStatusApplyConfiguration represents an declarative configuration of the WorkloadCertificateStatus type for use
// with apply.
type WorkloadCertificateStatusApplyConfiguration struct {
	Conditions                    []WorkloadCertificateConditionApplyConfiguration `json:"conditions,omitempty"`
	Certificate                   *string                                          `json:"certificate,omitempty"`
	CertificateObservedGeneration *int64                                           `json:"certificateObservedGeneration,omitempty"`
	NotBefore                     *v1.Time                                         `json:"notBefore,omitempty"`
	NotAfter                      *v1.Time                                         `json:"notAfter,omitempty"`
	BeginRefreshAt                *v1.Time                                         `json:"beginRefreshAt,omitempty"`
}

// WorkloadCertificateStatusApplyConfiguration constructs an declarative configuration of the WorkloadCertificateStatus type for use with
// apply.
func WorkloadCertificateStatus() *WorkloadCertificateStatusApplyConfiguration {
	return &WorkloadCertificateStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *WorkloadCertificateStatusApplyConfiguration) WithConditions(values ...*WorkloadCertificateConditionApplyConfiguration) *WorkloadCertificateStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithCertificate sets the Certificate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Certificate field is set to the value of the last call.
func (b *WorkloadCertificateStatusApplyConfiguration) WithCertificate(value string) *WorkloadCertificateStatusApplyConfiguration {
	b.Certificate = &value
	return b
}

// WithCertificateObservedGeneration sets the CertificateObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateObservedGeneration field is set to the value of the last call.
func (b *WorkloadCertificateStatusApplyConfiguration) WithCertificateObservedGeneration(value int64) *WorkloadCertificateStatusApplyConfiguration {
	b.CertificateObservedGeneration = &value
	return b
}

// WithNotBefore sets the NotBefore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotBefore field is set to the value of the last call.
func (b *WorkloadCertificateStatusApplyConfiguration) WithNotBefore(value v1.Time) *WorkloadCertificateStatusApplyConfiguration {
	b.NotBefore = &value
	return b
}

// WithNotAfter sets the NotAfter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotAfter field is set to the value of the last call.
func (b *WorkloadCertificateStatusApplyConfiguration) WithNotAfter(value v1.Time) *WorkloadCertificateStatusApplyConfiguration {
	b.NotAfter = &value
	return b
}

// WithBeginRefreshAt sets the BeginRefreshAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BeginRefreshAt field is set to the value of the last call.
func (b *WorkloadCertificateStatusApplyConfiguration) WithBeginRefreshAt(value v1.Time) *WorkloadCertificateStatusApplyConfiguration {
	b.BeginRefreshAt = &value
	return b
}
