/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "k8s.io/api/certificates/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	certificatesv1alpha1 "k8s.io/client-go/applyconfigurations/certificates/v1alpha1"
	scheme "k8s.io/client-go/kubernetes/scheme"
	rest "k8s.io/client-go/rest"
)

// WorkloadCertificatesGetter has a method to return a WorkloadCertificateInterface.
// A group's client should implement this interface.
type WorkloadCertificatesGetter interface {
	WorkloadCertificates(namespace string) WorkloadCertificateInterface
}

// WorkloadCertificateInterface has methods to work with WorkloadCertificate resources.
type WorkloadCertificateInterface interface {
	Create(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.CreateOptions) (*v1alpha1.WorkloadCertificate, error)
	Update(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.UpdateOptions) (*v1alpha1.WorkloadCertificate, error)
	UpdateStatus(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.UpdateOptions) (*v1alpha1.WorkloadCertificate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WorkloadCertificate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WorkloadCertificateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkloadCertificate, err error)
	Apply(ctx context.Context, workloadCertificate *certificatesv1alpha1.WorkloadCertificateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkloadCertificate, err error)
	ApplyStatus(ctx context.Context, workloadCertificate *certificatesv1alpha1.WorkloadCertificateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkloadCertificate, err error)
	WorkloadCertificateExpansion
}

// workloadCertificates implements WorkloadCertificateInterface
type workloadCertificates struct {
	client rest.Interface
	ns     string
}

// newWorkloadCertificates returns a WorkloadCertificates
func newWorkloadCertificates(c *CertificatesV1alpha1Client, namespace string) *workloadCertificates {
	return &workloadCertificates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workloadCertificate, and returns the corresponding workloadCertificate object, and an error if there is any.
func (c *workloadCertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkloadCertificates that match those selectors.
func (c *workloadCertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkloadCertificateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkloadCertificateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workloadcertificates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workloadCertificates.
func (c *workloadCertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workloadcertificates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a workloadCertificate and creates it.  Returns the server's representation of the workloadCertificate, and an error, if there is any.
func (c *workloadCertificates) Create(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.CreateOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workloadcertificates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workloadCertificate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a workloadCertificate and updates it. Returns the server's representation of the workloadCertificate, and an error, if there is any.
func (c *workloadCertificates) Update(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.UpdateOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(workloadCertificate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workloadCertificate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *workloadCertificates) UpdateStatus(ctx context.Context, workloadCertificate *v1alpha1.WorkloadCertificate, opts v1.UpdateOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(workloadCertificate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(workloadCertificate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the workloadCertificate and deletes it. Returns an error if one occurs.
func (c *workloadCertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workloadCertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workloadcertificates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched workloadCertificate.
func (c *workloadCertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkloadCertificate, err error) {
	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied workloadCertificate.
func (c *workloadCertificates) Apply(ctx context.Context, workloadCertificate *certificatesv1alpha1.WorkloadCertificateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	if workloadCertificate == nil {
		return nil, fmt.Errorf("workloadCertificate provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(workloadCertificate)
	if err != nil {
		return nil, err
	}
	name := workloadCertificate.Name
	if name == nil {
		return nil, fmt.Errorf("workloadCertificate.Name must be provided to Apply")
	}
	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *workloadCertificates) ApplyStatus(ctx context.Context, workloadCertificate *certificatesv1alpha1.WorkloadCertificateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WorkloadCertificate, err error) {
	if workloadCertificate == nil {
		return nil, fmt.Errorf("workloadCertificate provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(workloadCertificate)
	if err != nil {
		return nil, err
	}

	name := workloadCertificate.Name
	if name == nil {
		return nil, fmt.Errorf("workloadCertificate.Name must be provided to Apply")
	}

	result = &v1alpha1.WorkloadCertificate{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("workloadcertificates").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
